### ISSUE TITLE
CETE(feature_base) on trecr_qa dataset MAP 

### ISSUE THREAD

**Issue by ZhqZhqZhq** [tahmedge/CETE-LREC#2]
Hi @tahmedge 
I ran your CETE(BERT_base,feature_base) code and found that
MAP on trecr_qa is 0.710
My parameter are the same as in your paper：
d_ff = 768
h = 6
The accuracy value is far from 0.799 on the paper，Please tell me if it is the parameter reason？

**Comment by tahmedge** [comment]
Hi, were you able to load the contextualized embeddings properly?

**Comment by ZhqZhqZhq** [comment]
> Hi, were you able to load the contextualized embeddings properly?

yes, I am able to load bert embeddings properly

**Comment by tahmedge** [comment]
The result is supposed to be reproduced. What were the values in your [config.py](https://github.com/tahmedge/CETE-LREC/blob/master/CETE%20Feature-Based/Model_Transformer/config.py) file? 

Moreover, one probable reason for not being able to reproduce the result could possibly due to the incorrect mapping of each sentence in the dataset to the contextualized embedding. This is my opinion since your result is more similar to the baseline model used for the feature-based approach.

**Comment by ZhqZhqZhq** [comment]
> The result is supposed to be reproduced. What were the values in your [config.py](https://github.com/tahmedge/CETE-LREC/blob/master/CETE%20Feature-Based/Model_Transformer/config.py) file?
> 
> Moreover, one probable reason for not being able to reproduce the result could possibly due to the incorrect mapping of each sentence in the dataset to the contextualized embedding. This is my opinion since your result is more similar to the baseline model used for the feature-based approach.



> The result is supposed to be reproduced. What were the values in your [config.py](https://github.com/tahmedge/CETE-LREC/blob/master/CETE%20Feature-Based/Model_Transformer/config.py) file?
> 
> Moreover, one probable reason for not being able to reproduce the result could possibly due to the incorrect mapping of each sentence in the dataset to the contextualized embedding. This is my opinion since your result is more similar to the baseline model used for the feature-based approach.

Thank you very much for your suggestion, I will try again

**Comment by ZhqZhqZhq** [comment]
> > The result is supposed to be reproduced. What were the values in your [config.py](https://github.com/tahmedge/CETE-LREC/blob/master/CETE%20Feature-Based/Model_Transformer/config.py) file?
> > Moreover, one probable reason for not being able to reproduce the result could possibly due to the incorrect mapping of each sentence in the dataset to the contextualized embedding. This is my opinion since your result is more similar to the baseline model used for the feature-based approach.
> 
> > The result is supposed to be reproduced. What were the values in your [config.py](https://github.com/tahmedge/CETE-LREC/blob/master/CETE%20Feature-Based/Model_Transformer/config.py) file?
> > Moreover, one probable reason for not being able to reproduce the result could possibly due to the incorrect mapping of each sentence in the dataset to the contextualized embedding. This is my opinion since your result is more similar to the baseline model used for the feature-based approach.
> 
> Thank you very much for your suggestion, I will try again



> The result is supposed to be reproduced. What were the values in your [config.py](https://github.com/tahmedge/CETE-LREC/blob/master/CETE%20Feature-Based/Model_Transformer/config.py) file?
> 
> Moreover, one probable reason for not being able to reproduce the result could possibly due to the incorrect mapping of each sentence in the dataset to the contextualized embedding. This is my opinion since your result is more similar to the baseline model used for the feature-based approach.



> The result is supposed to be reproduced. What were the values in your [config.py](https://github.com/tahmedge/CETE-LREC/blob/master/CETE%20Feature-Based/Model_Transformer/config.py) file?
> 
> Moreover, one probable reason for not being able to reproduce the result could possibly due to the incorrect mapping of each sentence in the dataset to the contextualized embedding. This is my opinion since your result is more similar to the baseline model used for the feature-based approach.

Very lucky to be able to read this paper. I try it again,but I still fail,the map still did not reach value in paper.  please help me,I will be very grateful,I load contextualized embedding successfully ,my config as follows:
N = 6 #6 in Transformer Paper
    d_model = 768 #512 in Transformer Paper
    d_ff = 768 #2048 in Transformer Paper
    embed_size=768
    h = 6
    dropout = 0.10
    output_size = 1
    lr = 0.00005
    max_epochs = 6
    batch_size = 32
    max_sen_len = 100
    acc=0 #1 for msrp, 0 for trec
    multiplyby=100
    hidden_layers = 2
    hidden_size = 768
    bidirectional = True
    dropout_keep = 0.1
    model=0 #0 for transformer, 1 for blstm
    emb="/content/berttrecr"
    EmbeddingType = "Contextualized" #Otherwise, EmbeddingType="Contextualized" or "Baseline"
    data="trecr"

**Comment by tahmedge** [comment]
Hey, the issue might have occurred if you used the code from the previous commit where the lines from 88 to 99 were uncommented in this [file](https://github.com/tahmedge/CETE-LREC/blob/af3d696809d3f452e93652ef0b1ee76559456fdf/CETE%20Feature-Based/Model_Transformer/model.py#L86) to conduct the ablation test mentioned in the paper.

I have commented these lines now and hopefully you will be able to reproduce the result similar to what was mentioned in the paper.

**Comment by cxx-cindy** [comment]
> Hi @tahmedge
> I ran your CETE(BERT_base,feature_base) code and found that
> MAP on trecr_qa is 0.710
> My parameter are the same as in your paper：
> d_ff = 768
> h = 6
> The accuracy value is far from 0.799 on the paper，Please tell me if it is the parameter reason？

Hello, I also ran the feature-based code and found that there was an error. Did you change any code? I made this mistake：
Traceback (most recent call last):
  File "D:/研究生/论文代码/Contextualized Embeddings based Transformer Encoder for Sentence Similarity Modeling in Answer Selection Task/CETE-LREC-master/CETE Feature-Based/Model_Transformer/train.py", line 4, in <module>
    from utils import *
  File "D:\研究生\论文代码\Contextualized Embeddings based Transformer Encoder for Sentence Similarity Modeling in Answer Selection Task\CETE-LREC-master\CETE Feature-Based\Model_Transformer\utils.py", line 16, in <module>
    from train import return_file_name
  File "D:\研究生\论文代码\Contextualized Embeddings based Transformer Encoder for Sentence Similarity Modeling in Answer Selection Task\CETE-LREC-master\CETE Feature-Based\Model_Transformer\train.py", line 6, in <module>
    from model import *
  File "D:\研究生\论文代码\Contextualized Embeddings based Transformer Encoder for Sentence Similarity Modeling in Answer Selection Task\CETE-LREC-master\CETE Feature-Based\Model_Transformer\model.py", line 14, in <module>
    from train import return_file_name,return_emb1,return_emb2
ImportError: cannot import name 'return_file_name'

Process finished with exit code 1
