### ISSUE TITLE
code

### ISSUE THREAD

**Issue by cxx-cindy** [tahmedge/CETE-LREC#7]
Hello, when I execute feature-based code, I report an error. What's going on? In addition, I would like to ask about EMB = "E: / h5py data / Bert"_ Does file / Bert "in config.py need to be downloaded by yourself? Where can I download it?

error：
D:\Anaconda\envs\transformer\python.exe "D:/研究生/论文代码/Contextualized Embeddings based Transformer Encoder for Sentence Similarity Modeling in Answer Selection Task/CETE-LREC-master/CETE Feature-Based/Model_Transformer/train.py"
Traceback (most recent call last):
  File "D:/研究生/论文代码/Contextualized Embeddings based Transformer Encoder for Sentence Similarity Modeling in Answer Selection Task/CETE-LREC-master/CETE Feature-Based/Model_Transformer/train.py", line 4, in <module>
    from utils import *
  File "D:\研究生\论文代码\Contextualized Embeddings based Transformer Encoder for Sentence Similarity Modeling in Answer Selection Task\CETE-LREC-master\CETE Feature-Based\Model_Transformer\utils.py", line 16, in <module>
    from train import return_file_name
  File "D:\研究生\论文代码\Contextualized Embeddings based Transformer Encoder for Sentence Similarity Modeling in Answer Selection Task\CETE-LREC-master\CETE Feature-Based\Model_Transformer\train.py", line 6, in <module>
    from model import *
  File "D:\研究生\论文代码\Contextualized Embeddings based Transformer Encoder for Sentence Similarity Modeling in Answer Selection Task\CETE-LREC-master\CETE Feature-Based\Model_Transformer\model.py", line 14, in <module>
    from train import return_file_name,return_emb1,return_emb2
ImportError: cannot import name 'return_file_name'

Process finished with exit code 1

**Comment by HHL-445** [comment]
Hello, have you solved this problem? I imported the h5 file of bert downloaded by hugeface and still got an error. @cxx-cindy
